stages:
    - build
    - test
    - deploy

variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
    - export GRADLE_OPTS="-Dorg.gradle.daemon=false"
    - apt-get update -qy
    - apt-get install -y openjdk-17-jdk
    - export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
    - chmod +x gradlew
    - ./gradlew assembleAospOmega

build:
    stage: build
    interruptible: true
    script:
        - apt-get update -qy
        - apt-get install -y openjdk-17-jdk
        - export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
        - chmod +x gradlew
        - ./gradlew assembleAospOmega
    cache:    
        paths:
            - .gradle/caches
            - .gradle/wrapper
    artifacts:
        paths:
            - build/outputs/apk/aospOmega/debug/*.apk
        expire_in: 
            1 week

    after_script:
        - ARTIFACT_PATHNAME_APK=$(ls build/outputs/apk/aospOmega/debug/*.apk | head -n 1)
        - ARTIFACT_NAME_APK=$(basename $ARTIFACT_PATHNAME_APK)
        - echo "ARTIFACT_NAME_APK is ${ARTIFACT_NAME_APK}"
        - echo "ARTIFACT_PATHNAME_APK=${ARTIFACT_PATHNAME_APK}" >> $CI_JOB_ENV
        - echo "ARTIFACT_NAME_APK=${ARTIFACT_NAME_APK}" >> $CI_JOB_ENV

test:
    stage: test
    needs:
        [build]
    interruptible: true
    script:
        - ./gradlew -Pci --console=plain :app:testDebug

deploy:
    stage: deploy
    needs:
        [build, test]
    interruptible: true
    script:
        - echo "Configure to send to Telegram channel"
